const express = require('express');
const router = express.Router();
const passport = require('passport');
const teacherController = require('../controllers/teacherController');
const courseController = require('../controllers/courseController');
const quizController = require('../controllers/quizController');
const questionController = require('../controllers/questionController');
router.get('/signup',teacherController.signup);
router.get('/login',teacherController.login);
router.get('/courses',courseController.courses);
router.get('/course/:id',courseController.courseProfile);
router.get('/course/delete/:id',courseController.deleteCourse);
router.post('/course/:id/addquiz',quizController.addQuiz);
router.get('/course/:id/deletequiz/:id',quizController.deletequiz);
router.get('/course/:id/addquestion',questionController.questionPage); 
router.post('/signin',passport.authenticate('teacher',{failureRedirect:'/teacher/login'}),teacherController.signin);
router.post('/create',teacherController.create);
router.post('/courseCreate',courseController.addcourses);
module.exports = router;